coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8085
query.max-memory=1GB
query.max-memory-per-node=768MB
query.max-total-memory-per-node=1GB
discovery.uri=http://localhost:8085
