"""Seed script — creates and populates the demo SQLite database with sample data.

Data is generated by data/sample_tables/sample_data.py using a fixed random seed
so results are deterministic across runs and environments.

Row counts (>= 1000 total):
  Banking:    kredit_umkm (540), nasabah (80), cabang (25)
  Telco:      pelanggan (80), penggunaan_data (480), jaringan (20)
  Government: penduduk (40), anggaran_daerah (88), layanan_publik (132)
  Total:      1485 rows

Run once before starting the app:
    python data/sample_tables/seed_database.py
"""

import sqlite3
import sys
from pathlib import Path

# Allow direct execution: find sample_data in the same directory.
sys.path.insert(0, str(Path(__file__).parent))
from sample_data import generate_all  # noqa: E402

DB_PATH = Path(__file__).parent / "demo.db"


def seed() -> None:
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    data = generate_all()

    # ── BANKING: kredit_umkm ───────────────────────────────────────────
    cur.execute("DROP TABLE IF EXISTS kredit_umkm")
    cur.execute("""
        CREATE TABLE kredit_umkm (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            nasabah_id  INTEGER,
            wilayah     TEXT,
            segmen      TEXT,
            outstanding REAL,
            kualitas    TEXT,
            bulan       TEXT
        )
    """)
    cur.executemany(
        "INSERT INTO kredit_umkm (nasabah_id,wilayah,segmen,outstanding,kualitas,bulan) VALUES (?,?,?,?,?,?)",
        data["kredit_umkm"],
    )

    # ── BANKING: nasabah ───────────────────────────────────────────────
    cur.execute("DROP TABLE IF EXISTS nasabah")
    cur.execute("""
        CREATE TABLE nasabah (
            id              INTEGER PRIMARY KEY,
            nama            TEXT,
            segmen          TEXT,
            wilayah         TEXT,
            total_eksposur  REAL,
            rating_internal TEXT,
            tanggal_onboard TEXT
        )
    """)
    cur.executemany("INSERT INTO nasabah VALUES (?,?,?,?,?,?,?)", data["nasabah"])

    # ── BANKING: cabang ────────────────────────────────────────────────
    cur.execute("DROP TABLE IF EXISTS cabang")
    cur.execute("""
        CREATE TABLE cabang (
            id               INTEGER PRIMARY KEY,
            nama             TEXT,
            wilayah          TEXT,
            kota             TEXT,
            aktif            INTEGER,
            jumlah_nasabah   INTEGER,
            target_kredit    REAL,
            realisasi_kredit REAL
        )
    """)
    cur.executemany("INSERT INTO cabang VALUES (?,?,?,?,?,?,?,?)", data["cabang"])

    # ── TELCO: pelanggan ───────────────────────────────────────────────
    cur.execute("DROP TABLE IF EXISTS pelanggan")
    cur.execute("""
        CREATE TABLE pelanggan (
            id               INTEGER PRIMARY KEY,
            nama             TEXT,
            tipe             TEXT,
            paket            TEXT,
            wilayah          TEXT,
            status           TEXT,
            tanggal_aktivasi TEXT,
            churn_risk_score INTEGER,
            arpu_monthly     REAL
        )
    """)
    cur.executemany("INSERT INTO pelanggan VALUES (?,?,?,?,?,?,?,?,?)", data["pelanggan"])

    # ── TELCO: penggunaan_data ─────────────────────────────────────────
    cur.execute("DROP TABLE IF EXISTS penggunaan_data")
    cur.execute("""
        CREATE TABLE penggunaan_data (
            id             INTEGER PRIMARY KEY,
            pelanggan_id   INTEGER,
            bulan          TEXT,
            kuota_gb       REAL,
            penggunaan_gb  REAL,
            kecepatan_mbps REAL,
            biaya_tambahan REAL
        )
    """)
    cur.executemany("INSERT INTO penggunaan_data VALUES (?,?,?,?,?,?,?)", data["penggunaan_data"])

    # ── TELCO: jaringan ────────────────────────────────────────────────
    cur.execute("DROP TABLE IF EXISTS jaringan")
    cur.execute("""
        CREATE TABLE jaringan (
            id             INTEGER PRIMARY KEY,
            wilayah        TEXT,
            kota           TEXT,
            tipe_jaringan  TEXT,
            jumlah_bts     INTEGER,
            kapasitas_mbps REAL,
            utilisasi_pct  REAL,
            status         TEXT
        )
    """)
    cur.executemany("INSERT INTO jaringan VALUES (?,?,?,?,?,?,?,?)", data["jaringan"])

    # ── GOVERNMENT: penduduk ───────────────────────────────────────────
    cur.execute("DROP TABLE IF EXISTS penduduk")
    cur.execute("""
        CREATE TABLE penduduk (
            id         INTEGER PRIMARY KEY,
            kecamatan  TEXT,
            kabupaten  TEXT,
            provinsi   TEXT,
            jumlah     INTEGER,
            laki_laki  INTEGER,
            perempuan  INTEGER,
            tahun      INTEGER
        )
    """)
    cur.executemany("INSERT INTO penduduk VALUES (?,?,?,?,?,?,?,?)", data["penduduk"])

    # ── GOVERNMENT: anggaran_daerah ────────────────────────────────────
    cur.execute("DROP TABLE IF EXISTS anggaran_daerah")
    cur.execute("""
        CREATE TABLE anggaran_daerah (
            id           INTEGER PRIMARY KEY,
            satuan_kerja TEXT,
            program      TEXT,
            pagu         REAL,
            realisasi    REAL,
            triwulan     TEXT,
            tahun        INTEGER
        )
    """)
    cur.executemany("INSERT INTO anggaran_daerah VALUES (?,?,?,?,?,?,?)", data["anggaran_daerah"])

    # ── GOVERNMENT: layanan_publik ─────────────────────────────────────
    cur.execute("DROP TABLE IF EXISTS layanan_publik")
    cur.execute("""
        CREATE TABLE layanan_publik (
            id                  INTEGER PRIMARY KEY,
            jenis_layanan       TEXT,
            satuan_kerja        TEXT,
            jumlah_permohonan   INTEGER,
            selesai_tepat_waktu INTEGER,
            kepuasan_pct        REAL,
            rata_waktu_hari     REAL,
            bulan               TEXT
        )
    """)
    cur.executemany("INSERT INTO layanan_publik VALUES (?,?,?,?,?,?,?,?)", data["layanan_publik"])

    conn.commit()
    conn.close()

    total = sum(len(v) for v in data.values())
    print(f"Demo database seeded at: {DB_PATH}")
    print(f"Total rows: {total}")
    print(f"  Banking:    kredit_umkm ({len(data['kredit_umkm'])}), nasabah ({len(data['nasabah'])}), cabang ({len(data['cabang'])})")
    print(f"  Telco:      pelanggan ({len(data['pelanggan'])}), penggunaan_data ({len(data['penggunaan_data'])}), jaringan ({len(data['jaringan'])})")
    print(f"  Government: penduduk ({len(data['penduduk'])}), anggaran_daerah ({len(data['anggaran_daerah'])}), layanan_publik ({len(data['layanan_publik'])})")


if __name__ == "__main__":
    seed()
